# Tên ứng dụng (cái này để nguyên cũng được)
spring.application.name=badminton-platform

# Cấu hình kết nối tới PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/badminton_db
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# Hibernate tự động quản lý bảng (quan trọng để nó tự tạo bảng cho bạn)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0